# Referrence: https://synuns.tistory.com/75
name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.REACT_APP_AUTH_CLIENT_ID }}" > .env
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t lionnoil628/travel-planner-front .
      - name: Push Docker Image
        run: docker push lionnoil628/travel-planner-front:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull lionnoil628/travel-planner-front:latest
      - name: Delete existing container
        run: docker rm -f reactContainer
      - name: Run container
        run: docker run -d -p 80:80 --name reactContainer lionnoil628/travel-planner-front
